# Set Defaule User
export DEFAULT_USER=chris
# Set up aliases
alias ls="ls --color"
#alias ll="ls -al --color"
# For E terminal
#alias ls="tyls"
# History Size and Location
export HISTSIZE=500
export HISTFILE="$HOME/.zsh_history"
# Make sure history saves
export SAVEHIST=$HISTSIZE
# Histor ignore all dupes
setopt hist_ignore_all_dups
# History ignore commands starting with space
setopt hist_ignore_space
# Enabling Portage completions and gentoo prompt
autoload -U compinit promptinit
compinit
promptinit; prompt gentoo
# Enable completion style
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
# Enable comman correction
setopt correctall
# Enabling competion cache
zstyle ':completion::complete:*' use-cache 1
# Bring in powerline
. /usr/share/zsh/site-contrib/powerline.zsh
. ~/.zshtheme/agnoster-zsh-theme/agnoster.zsh-theme
# Bring in autocomplete
. ~/.zshtheme/zsh-autosuggestions/zsh-autosuggestions.zsh

